Updated commit hooks to be less annoying
[skip ci]

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,40 +1,47 @@
 #!/bin/bash
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$" | tr '\n' ' ')
+STAGED_SCRIPTS=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$" | tr '\n' ' ')
+STAGED_DATA=$(git diff --cached --name-only --diff-filter=ACM | grep ".json$" | tr '\n' ' ')
 
-if [[ "$STAGED_FILES" = "" ]]; then
+# if [[ "$STAGED_FILES" = "" ]]; then
+#   exit 0
+# fi
+
+if [[ "$STAGED_SCRIPTS" != "" ]]; then
+  PASS=true
+
+  echo "Validating Javascript:"
+
+  ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
+
+  "$ESLINT" "$STAGED_FILES"
+  if [[ "$?" == 0 ]]; then
+    echo -e "\t\033[32mESLint Passed: $STAGED_FILES\033[0m"
+  else
+    PASS=false
+  fi
+
+  if ! $PASS; then
+    echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
+    exit 1
+  fi
+
+  if [[ "$?" != 0 ]]; then
+    exit $?
+  fi
+fi
+
+if [[ "$STAGED_SCRIPTS" != "" || "$STAGED_DATA" != "" ]]; then
+  echo "Creating docs"
+  npm run docs
+
+  if [[ "$?" != 0 ]]; then
+    exit $?
+  fi
+
+  git add docs/
+
+  exit $?
+else
   exit 0
 fi
-
-PASS=true
-
-echo "Validating Javascript:"
-
-ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
-
-"$ESLINT" "$STAGED_FILES"
-if [[ "$?" == 0 ]]; then
-  echo -e "\t\033[32mESLint Passed: $STAGED_FILES\033[0m"
-else
-  PASS=false
-fi
-
-if ! $PASS; then
-  echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
-  exit 1
-fi
-
-if [[ "$?" != 0 ]]; then
-  exit $?
-fi
-
-echo "Creating docs"
-npm run docs
-
-if [[ "$?" != 0 ]]; then
-  exit $?
-fi
-
-git add docs/
-
-exit $?
